baseURL = "https://techprocurement.org/"
languageCode = "en-us"
title = "Tech Procurement for the Incoming Govvie"
theme = "book"



[params]
    description = "A book of actionable information about how to procure tech in the federal government"
    title = "Tech Procurement for the Incoming Govvie"

    BookMenuBundle = '/menu'
    BookSection = 'chapters'